### ISSUE TITLE
How about DW3000

### ISSUE THREAD

**Issue by kallu1294** [jonathanrjpereira/DWM1000-Real-Time-Localization-System#4]
Hi
I want to implement tag and anchor for finding the location using DWM3000.
Any idea how can i do that.?

I have searched lot for DWM3000 but i couldn't  find anywhere so i asked here for the help
Sorry

**Comment by jonathanrjpereira** [comment]
I haven't had a chance to go through the DWM3000 docs, but I'm certain that it's HAL would be similar to the DWM1001.
